trunk:
SVNAdminArea16:
 - addTreeConflict(): improve 'tree conflict already exists'
   error: include the path of.svn catalog where 
   the conflict is created to the error message.